services:
  - type: web
    name: flask-weather-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: flask_weather_db
          property: connectionString

databases:
  - name: flask_weather_db
    databaseName: weather_db
    user: weather_user
    plan: free
